### PR TITLE
Simplify pickling logic by using __reduce__ instead of copy_reg

### PR DESCRIPTION
**Pull request by mgedmin**
The pickles produced this way are identical to the old ones.

One reason for this is that [mongopersist](https://pypi.python.org/pypi/mongopersist) currently doesn't implement the full pickle semantics and doesn't pay attention to the reduction function registered with the copy_reg module, but it can handle `__reduce__` just fine.

### CODE REVIEW

**Comment by tseaver** [comment]
LGTM

**Comment by mgedmin** [comment]
I don't have the time to push this to completion (e.g. resolve the merge conflicts), sorry :/

**Comment by mgedmin** [comment]
Python 3.5 fails with `ImportError: No module named 'zope.interface'` which is that-bug-I'm-too-lazy-to-look-up with namespace packages.  We usually avoid by switching travis (and tox.ini) to run `zope-testrunner --test-path=src` instead of `python setup.py test`.

**Comment by icemac** [comment]
@mgedmin Now the tests are green. :)

**Comment by mgedmin** [comment]
Yes, but coveralls is unhappy ("Coverage decreased (-0.08%) to 94.703%") :/

**Comment by icemac** [comment]
@mgedmin Coverage should not be a problem. As you reduced the code needed for this feature this was expected.

**Comment by mgedmin** [comment]
You've convinced me to hit the merge button :)

**Pull request merged**
